# .gitlab-ci.yml

stages:
    - probe

workflow:
    rules:
        - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'

probe-step:
    stage: probe
    image: docker.io/gameplayer8/probe:latest
    script:
        - /usr/local/bin/probe
